service: sls-owunode
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getUsers:
    handler: index.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  getCars:
    handler: index.getCars
    events:
      - httpApi:
          path: /cars
          method: get